import { motion } from 'framer-motion';

// Framer Motion variants for staggered child animations
const container = {
  hidden: {},
  show: {
    transition: {
      staggerChildren: 0.1,
    }
  }
};

const item = {
  hidden: { opacity: 0, y: 20 },
  show: { opacity: 1, y: 0 }
};

const PlaceholderHero = ({ onNavigate }) => {
  return (
    <motion.section 
      variants={container}
      initial="hidden"
      animate="show"
      className="text-center py-16 md:py-24 lg:py-32 bg-white shadow-xl rounded-2xl transition duration-500 hover:shadow-2xl"
    >
      <div className="max-w-4xl mx-auto px-4">
        
        {/* Animated Heading */}
        <motion.h1 
          variants={item}
          className="text-4xl sm:text-5xl lg:text-7xl font-extrabold text-gray-900 leading-tight mb-4"
        >
          <span className="text-primary-brand">S-Forge</span>: Where Vision Meets Code Excellence
        </motion.h1>

        {/* Animated Subtitle */}
        <motion.p 
          variants={item}
          className="mt-6 text-lg sm:text-xl text-gray-600 mb-8 max-w-2xl mx-auto"
        >
          This is the core structure generated by the **Build Engine**. Highly responsive, performant, and ready for your unique strategic content.
        </motion.p>
        
        {/* Animated CTA Button */}
        <motion.div variants={item} className="flex justify-center space-x-4">
          <button 
            onClick={onNavigate}
            className="px-8 py-3 bg-primary-brand text-white font-semibold rounded-lg shadow-lg hover:bg-opacity-90 transition transform hover:scale-105 duration-300 focus:outline-none focus:ring-4 focus:ring-primary-brand focus:ring-opacity-50"
          >
            Explore Next Steps
          </button>
          <a
            href="https://github.com/solomough"
            target="_blank"
            rel="noopener noreferrer"
            className="px-8 py-3 bg-white border border-gray-300 text-gray-700 font-semibold rounded-lg shadow-lg hover:bg-gray-100 transition duration-300 transform hover:translate-y-[-2px] focus:outline-none focus:ring-4 focus:ring-gray-300 focus:ring-opacity-50"
          >
            View Creator Profile
          </a>
        </motion.div>

      </div>
    </motion.section>
  );
};

export default PlaceholderHero;
